"""Generate SYNTHETIC paired (url, html, label) data to smoke-test the pipeline.

!!  Do not report numbers from this data. It is generated by rules similar to the
!!  ones the detector uses, so the scores are meaningless as evidence. Use it only
!!  to check that training, evaluation and the API run end to end before you have
!!  a real dataset (see scripts/collect_dataset.py).
"""
from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

WORDS = ["river", "maple", "cloud", "pixel", "garden", "orbit", "harbor", "lumen", "atlas", "bright",
         "copper", "nova", "delta", "summit", "willow", "ember", "quartz", "meadow", "falcon", "tidal"]
BRANDS = ["paypal", "amazon", "google", "microsoft", "netflix", "sbi", "hdfc", "paytm", "apple", "irctc"]
GOOD_TLDS = ["com", "org", "in", "net", "io", "co.uk"]
BAD_TLDS = ["xyz", "top", "click", "icu", "tk", "buzz", "co.in", "com"]
KEYS = ["login", "verify", "secure", "account", "update", "kyc", "billing"]


def _benign(rng: random.Random, i: int) -> dict:
    name = "-".join(rng.sample(WORDS, rng.choice([1, 1, 1, 2])))
    host = f"{'www.' if rng.random() < 0.5 else ''}{name}.{rng.choice(GOOD_TLDS)}"
    path = "/" + "/".join(rng.choice(WORDS) for _ in range(rng.randint(0, 3)))
    is_login = rng.random() < 0.15  # legitimate login pages exist and must be in the benign set
    if is_login:
        path = "/login"
    if rng.random() < 0.1:  # some benign URLs look untidy
        path += "?ref=" + "".join(rng.choice("abcdef0123456789") for _ in range(30))
    url = f"{'https' if rng.random() < 0.93 else 'http'}://{host}{path}"
    form = ""
    if is_login:
        form = '<form action="/session" method="post"><input name="user"><input type="password" name="pw"></form>'
    html = (f"<html><head><title>{name.title()}</title></head><body><h1>{name}</h1>"
            f"<a href='/about'>About</a><a href='/blog'>Blog</a><a href='/contact'>Contact</a>"
            f"<img src='/logo.png'>{form}<p>Welcome to our site.</p></body></html>")
    return {"url": url, "label": 0, "html": html}


def _phish(rng: random.Random, i: int) -> dict:
    clean = rng.random() < 0.25  # a quarter look lexically clean: only the page gives them away
    brand = rng.choice(BRANDS)
    if clean:
        host = "-".join(rng.sample(WORDS, 2)) + "." + rng.choice(GOOD_TLDS)
        path = "/" + rng.choice(WORDS)
        scheme = "https"
    else:
        host = f"{brand}-{rng.choice(KEYS)}.{rng.choice(WORDS)}-{rng.choice(KEYS)}.{rng.choice(BAD_TLDS)}"
        path = f"/{rng.choice(KEYS)}/{rng.choice(KEYS)}"
        scheme = "http" if rng.random() < 0.6 else "https"
    url = f"{scheme}://{host}{path}"
    hard = rng.random() < 0.12  # page without obvious cues
    if hard:
        html = "<html><head><title>Loading</title></head><body><a href='/x'>Continue</a></body></html>"
    else:
        html = (f"<html><head><title>{brand.title()} - Sign in</title></head><body>"
                f"<h1>{brand}</h1><p>Your account has been suspended. Verify your account immediately.</p>"
                f"<form action='https://{rng.choice(WORDS)}-collect.{rng.choice(BAD_TLDS)}/p.php'>"
                f"<input name='email'><input type='password' name='pw'></form>"
                f"<a href='#'>Help</a><a href='#'>Terms</a><a href='#'>Privacy</a></body></html>")
    return {"url": url, "label": 1, "html": html}


def make_rows(n: int, seed: int = 7, phish_share: float = 0.5) -> list[dict]:
    rng = random.Random(seed)
    rows = []
    for i in range(n):
        r = _phish(rng, i) if rng.random() < phish_share else _benign(rng, i)
        r["ts"] = 1_700_000_000 + i * 60  # increasing timestamps -> time-based split works
        rows.append(r)
    return rows


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--n", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--jsonl", default="data/synthetic_smoke.jsonl")
    ap.add_argument("--csv", default="data/synthetic_smoke_urls.csv")
    a = ap.parse_args()
    rows = make_rows(a.n, a.seed)
    Path(a.jsonl).parent.mkdir(parents=True, exist_ok=True)
    with open(a.jsonl, "w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    with open(a.csv, "w", encoding="utf-8") as f:
        f.write("url,label,ts\n")
        for r in rows:
            f.write(f"{r['url']},{r['label']},{r['ts']}\n")
    print(f"Wrote {len(rows)} SYNTHETIC rows -> {a.jsonl}, {a.csv}  (smoke test only; do not report results)")


if __name__ == "__main__":
    main()
